print("##########DIÀLOGO#########")
input("Digita")
print("Hello")
print("Hello oq mn?")
print("Adivinha")
print("N me diga q é...")
print("SIM! Hello World")
print("Hello")
print("Hello oq mn?")
print("Adivinha")
print("N me diga q é...")
print("SIM! Hello World")